name: Actions Runner Controller Demo
on:
  workflow_dispatch:

jobs:
  Explore-GitHub-Actions:
    # Uses the ARC runner scale set installation name: lama-arc-runner-set
    runs-on: lama-arc-runner-set
    permissions: {}
    steps:
    - run: echo "🎉 This job uses runner scale set runners!"
