name: Actions Runner Controller Demo
on:
  workflow_dispatch:

jobs:
  Explore-GitHub-Actions:
    # Uses the ARC runner scale set installation name: lama-arc-runner-set
    runs-on: yocto-runner-set
    container:
      image: ubuntu:24.04
    permissions: {}
    steps:
    - run: echo "🎉 This job uses runner scale set runners!"
    - run: ls -alh /
    - run: ls -alh /__*
    - run: ls -alh /__w/_tool
    - run: mount
    - run: ls -alh /github/*
